
server:
  port: 32501

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: testers-service
  kafka:
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    bootstrap-servers: broker:29092,localhost:9092

booksclient:
  ribbon:
    listOfServers: books-service:32500,localhost:32800
    ServerListRefreshInterval: 3000

log:
  topic:
    name: testers-service-activity
